[package]
name = "hello_wasm"
version = "0.1.0"
authors = ["Michael Klishevich <busation@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

# new material
[lib]
crate-type = ["cdylib"]